#!/usr/bin/env python
import pwd

def get_student_user():
  try:
    return pwd.getpwuid(502)[0]
  except:
    return None

u_student = get_student_user()
if u_student is None:
  print ""
else:
  print u_student
